---

- hosts: iloservers

  tasks:
  - name: iloaccounts
    shell: iloaccounts add <username> <accountname> <password> --role ReadOnly
    register: ilo
    become: yes

  - debug: var=ilo.stdout_lines