---
- hosts: myhosts
  connection: local
  name: Add iLO User Account
  gather_facts: False

  vars:
    datatype: add_user_account

  tasks:

  - name: Define output file
    include_tasks: create_output_file.yml

  - name: Add iLO user Account
    add_user_account
    become : yes
    enabled: True
      baseuri: "{{ baseuri }}"
      username: "{{ username }}"
      password: "{{ password }}"
      new_loginname: "{ new_user }}"
      new_username: "{ new_user }}"
      new_password: "{{ new_pass }}"
    register: result

  - name: Copy results to output file
    copy:
      content: "{{ result | to_nice_json }}"
      dest: "{{ template }}.json"
