---
- hosts: myhosts
  connection: local
  name: Bios Revert Default
  gather_facts: False

  vars:
    datatype: bios_revert_default

  tasks:

  - name: Define output file
    include_tasks: create_output_file.yml

  - name: Get revert default
    bios_revert_default:
    become : yes
    enabled: True
      baseuri: "{{ baseuri }}"
      username: "{{ username }}"
      password: "{{ password }}"
    register: result

  - name: Copy results to output file
    copy:
      content: "{{ result | to_nice_json }}"
      dest: "{{ template }}.json"
