---
- hosts: myhosts
  connection: local
  name: Enable Secure Boot
  gather_facts: False

  vars:
    datatype: enable_secureboot

  tasks:

  - name: Define output file
    include_tasks: create_output_file.yml

  - name: Enable Secure Boot
    enable_secure_boot:
    become : yes
    enabled: True
      baseuri: "{{ baseuri }}"
      username: "{{ username }}"
      password: "{{ password }}"
      boot_enabled : True
      bios_password: None
    register: result

  - name: Copy results to output file
    copy:
      content: "{{ result | to_nice_json }}"
      dest: "{{ template }}.json"
