---
- hosts: myhosts
  connection: local
  name: Get AHS
  gather_facts: False

  vars:
    datatype: get_ahs
    set_fact: ahs_name={{rootdir}}/{{host}}/{{host}}_{{datatype}}_{{timestamp}} 

  tasks:

  - name: Define output file
    include_tasks: create_output_file.yml

  - name: Get ahs
    get_ahs:
    become : yes
    enabled: True
      baseuri: "{{ baseuri }}"
      username: "{{ username }}"
      password: "{{ password }}"
      ahs_file_name: "{{ ahs_name }}"
    register: result

  - name: Copy results to output file
    copy:
      content: "{{ result | to_nice_json }}"
      dest: "{{ template }}.json"
